// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nuxeo.proto

package org.nuxeo.micro.repo.proto;

public interface DocumentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NuxeoClient.DocumentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string path = 2;</code>
   */
  java.lang.String getPath();
  /**
   * <code>string path = 2;</code>
   */
  com.google.protobuf.ByteString
      getPathBytes();
}
