// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nuxeo.proto

package org.nuxeo.micro.repo.proto;

public interface DocumentCreationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NuxeoClient.DocumentCreationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string path = 1;</code>
   */
  java.lang.String getPath();
  /**
   * <code>string path = 1;</code>
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.NuxeoClient.Document document = 4;</code>
   */
  boolean hasDocument();
  /**
   * <code>.NuxeoClient.Document document = 4;</code>
   */
  org.nuxeo.micro.repo.proto.Document getDocument();
  /**
   * <code>.NuxeoClient.Document document = 4;</code>
   */
  org.nuxeo.micro.repo.proto.DocumentOrBuilder getDocumentOrBuilder();
}
