// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nuxeo.proto

package org.nuxeo.micro.repo.proto;

public interface DocumentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NuxeoClient.Document)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string repositoryName = 1;</code>
   */
  java.lang.String getRepositoryName();
  /**
   * <code>string repositoryName = 1;</code>
   */
  com.google.protobuf.ByteString
      getRepositoryNameBytes();

  /**
   * <code>string uuid = 2;</code>
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 2;</code>
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>string name = 3;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string parentPath = 4;</code>
   */
  java.lang.String getParentPath();
  /**
   * <code>string parentPath = 4;</code>
   */
  com.google.protobuf.ByteString
      getParentPathBytes();

  /**
   * <code>string type = 5;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 5;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>repeated string facets = 6;</code>
   */
  java.util.List<java.lang.String>
      getFacetsList();
  /**
   * <code>repeated string facets = 6;</code>
   */
  int getFacetsCount();
  /**
   * <code>repeated string facets = 6;</code>
   */
  java.lang.String getFacets(int index);
  /**
   * <code>repeated string facets = 6;</code>
   */
  com.google.protobuf.ByteString
      getFacetsBytes(int index);

  /**
   * <code>repeated .NuxeoClient.Document.Schema schema = 7;</code>
   */
  java.util.List<org.nuxeo.micro.repo.proto.Document.Schema> 
      getSchemaList();
  /**
   * <code>repeated .NuxeoClient.Document.Schema schema = 7;</code>
   */
  org.nuxeo.micro.repo.proto.Document.Schema getSchema(int index);
  /**
   * <code>repeated .NuxeoClient.Document.Schema schema = 7;</code>
   */
  int getSchemaCount();
  /**
   * <code>repeated .NuxeoClient.Document.Schema schema = 7;</code>
   */
  java.util.List<? extends org.nuxeo.micro.repo.proto.Document.SchemaOrBuilder> 
      getSchemaOrBuilderList();
  /**
   * <code>repeated .NuxeoClient.Document.Schema schema = 7;</code>
   */
  org.nuxeo.micro.repo.proto.Document.SchemaOrBuilder getSchemaOrBuilder(
      int index);

  /**
   * <code>string state = 8;</code>
   */
  java.lang.String getState();
  /**
   * <code>string state = 8;</code>
   */
  com.google.protobuf.ByteString
      getStateBytes();

  /**
   * <code>string parentRef = 9;</code>
   */
  java.lang.String getParentRef();
  /**
   * <code>string parentRef = 9;</code>
   */
  com.google.protobuf.ByteString
      getParentRefBytes();

  /**
   * <code>string changeToken = 10;</code>
   */
  java.lang.String getChangeToken();
  /**
   * <code>string changeToken = 10;</code>
   */
  com.google.protobuf.ByteString
      getChangeTokenBytes();

  /**
   * <code>string title = 11;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 11;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>int64 lastModified = 12;</code>
   */
  long getLastModified();

  /**
   * <code>string versionLabel = 13;</code>
   */
  java.lang.String getVersionLabel();
  /**
   * <code>string versionLabel = 13;</code>
   */
  com.google.protobuf.ByteString
      getVersionLabelBytes();

  /**
   * <code>string lockOwner = 14;</code>
   */
  java.lang.String getLockOwner();
  /**
   * <code>string lockOwner = 14;</code>
   */
  com.google.protobuf.ByteString
      getLockOwnerBytes();

  /**
   * <code>int64 lockCreated = 15;</code>
   */
  long getLockCreated();

  /**
   * <code>bool isCheckedOut = 16;</code>
   */
  boolean getIsCheckedOut();

  /**
   * <code>map&lt;string, .NuxeoClient.Document.Property&gt; properties = 17;</code>
   */
  int getPropertiesCount();
  /**
   * <code>map&lt;string, .NuxeoClient.Document.Property&gt; properties = 17;</code>
   */
  boolean containsProperties(
      java.lang.String key);
  /**
   * Use {@link #getPropertiesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, org.nuxeo.micro.repo.proto.Document.Property>
  getProperties();
  /**
   * <code>map&lt;string, .NuxeoClient.Document.Property&gt; properties = 17;</code>
   */
  java.util.Map<java.lang.String, org.nuxeo.micro.repo.proto.Document.Property>
  getPropertiesMap();
  /**
   * <code>map&lt;string, .NuxeoClient.Document.Property&gt; properties = 17;</code>
   */

  org.nuxeo.micro.repo.proto.Document.Property getPropertiesOrDefault(
      java.lang.String key,
      org.nuxeo.micro.repo.proto.Document.Property defaultValue);
  /**
   * <code>map&lt;string, .NuxeoClient.Document.Property&gt; properties = 17;</code>
   */

  org.nuxeo.micro.repo.proto.Document.Property getPropertiesOrThrow(
      java.lang.String key);
}
