// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nuxeo.proto

package org.nuxeo.micro.repo.proto;

public final class NuxeoClientProto {
  private NuxeoClientProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NuxeoClient_DocumentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NuxeoClient_DocumentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NuxeoClient_DocumentCreationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NuxeoClient_DocumentCreationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NuxeoClient_QueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NuxeoClient_QueryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NuxeoClient_QueryResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NuxeoClient_QueryResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NuxeoClient_Document_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NuxeoClient_Document_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NuxeoClient_Document_Schema_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NuxeoClient_Document_Schema_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NuxeoClient_Document_Property_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NuxeoClient_Document_Property_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NuxeoClient_Document_Property_ScalarProperty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NuxeoClient_Document_Property_ScalarProperty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NuxeoClient_Document_Property_ComplexProperty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NuxeoClient_Document_Property_ComplexProperty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NuxeoClient_Document_Property_ComplexProperty_ComplexValueEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NuxeoClient_Document_Property_ComplexProperty_ComplexValueEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NuxeoClient_Document_PropertiesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NuxeoClient_Document_PropertiesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013nuxeo.proto\022\013NuxeoClient\"+\n\017DocumentRe" +
      "quest\022\n\n\002id\030\001 \001(\t\022\014\n\004path\030\002 \001(\t\"^\n\027Docum" +
      "entCreationRequest\022\014\n\004path\030\001 \001(\t\022\014\n\004name" +
      "\030\002 \001(\t\022\'\n\010document\030\004 \001(\0132\025.NuxeoClient.D" +
      "ocument\"\034\n\014QueryRequest\022\014\n\004nxql\030\001 \001(\t\"F\n" +
      "\013QueryResult\022\022\n\ntotalCount\030\001 \001(\003\022#\n\004docs" +
      "\030\n \003(\0132\025.NuxeoClient.Document\"\217\t\n\010Docume" +
      "nt\022\026\n\016repositoryName\030\001 \001(\t\022\014\n\004uuid\030\002 \001(\t" +
      "\022\014\n\004name\030\003 \001(\t\022\022\n\nparentPath\030\004 \001(\t\022\014\n\004ty" +
      "pe\030\005 \001(\t\022\016\n\006facets\030\006 \003(\t\022,\n\006schema\030\007 \003(\013",
      "2\034.NuxeoClient.Document.Schema\022\r\n\005state\030" +
      "\010 \001(\t\022\021\n\tparentRef\030\t \001(\t\022\023\n\013changeToken\030" +
      "\n \001(\t\022\r\n\005title\030\013 \001(\t\022\024\n\014lastModified\030\014 \001" +
      "(\003\022\024\n\014versionLabel\030\r \001(\t\022\021\n\tlockOwner\030\016 " +
      "\001(\t\022\023\n\013lockCreated\030\017 \001(\003\022\024\n\014isCheckedOut" +
      "\030\020 \001(\010\0229\n\nproperties\030\021 \003(\0132%.NuxeoClient" +
      ".Document.PropertiesEntry\032&\n\006Schema\022\014\n\004n" +
      "ame\030\001 \001(\t\022\016\n\006prefix\030\002 \001(\t\032\210\005\n\010Property\0225" +
      "\n\004type\030\001 \001(\0162\'.NuxeoClient.Document.Prop" +
      "erty.PropType\022\020\n\010multiple\030\002 \001(\010\022B\n\013scala",
      "rValue\030\003 \003(\0132-.NuxeoClient.Document.Prop" +
      "erty.ScalarProperty\022D\n\014complexValue\030\004 \003(" +
      "\0132..NuxeoClient.Document.Property.Comple" +
      "xProperty\032\205\001\n\016ScalarProperty\022\022\n\010strValue" +
      "\030\001 \001(\tH\000\022\022\n\010intValue\030\002 \001(\022H\000\022\025\n\013doubleVa" +
      "lue\030\003 \001(\001H\000\022\023\n\tbyteValue\030\004 \001(\014H\000\022\026\n\014bool" +
      "eanValue\030\005 \001(\010H\000B\007\n\005value\032\276\001\n\017ComplexPro" +
      "perty\022V\n\014complexValue\030\001 \003(\0132@.NuxeoClien" +
      "t.Document.Property.ComplexProperty.Comp" +
      "lexValueEntry\032S\n\021ComplexValueEntry\022\013\n\003ke",
      "y\030\001 \001(\t\022-\n\005value\030\002 \001(\0132\036.NuxeoClient.Doc" +
      "ument.Property:\0028\001\"`\n\010PropType\022\n\n\006STRING" +
      "\020\000\022\007\n\003INT\020\001\022\n\n\006DOUBLE\020\002\022\010\n\004DATE\020\003\022\010\n\004BOO" +
      "L\020\004\022\010\n\004BLOB\020\005\022\013\n\007COMPLEX\020\006\022\010\n\004BYTE\020\007\032Q\n\017" +
      "PropertiesEntry\022\013\n\003key\030\001 \001(\t\022-\n\005value\030\002 " +
      "\001(\0132\036.NuxeoClient.Document.Property:\0028\0012" +
      "\355\002\n\020NuxeoCoreSession\022D\n\013getDocument\022\034.Nu" +
      "xeoClient.DocumentRequest\032\025.NuxeoClient." +
      "Document\"\000\022O\n\016createDocument\022$.NuxeoClie" +
      "nt.DocumentCreationRequest\032\025.NuxeoClient",
      ".Document\"\000\022@\n\016updateDocument\022\025.NuxeoCli" +
      "ent.Document\032\025.NuxeoClient.Document\"\000\022>\n" +
      "\005query\022\031.NuxeoClient.QueryRequest\032\030.Nuxe" +
      "oClient.QueryResult\"\000\022@\n\016deleteDocument\022" +
      "\025.NuxeoClient.Document\032\025.NuxeoClient.Doc" +
      "ument\"\000B0\n\032org.nuxeo.micro.repo.protoB\020N" +
      "uxeoClientProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_NuxeoClient_DocumentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NuxeoClient_DocumentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NuxeoClient_DocumentRequest_descriptor,
        new java.lang.String[] { "Id", "Path", });
    internal_static_NuxeoClient_DocumentCreationRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_NuxeoClient_DocumentCreationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NuxeoClient_DocumentCreationRequest_descriptor,
        new java.lang.String[] { "Path", "Name", "Document", });
    internal_static_NuxeoClient_QueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_NuxeoClient_QueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NuxeoClient_QueryRequest_descriptor,
        new java.lang.String[] { "Nxql", });
    internal_static_NuxeoClient_QueryResult_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_NuxeoClient_QueryResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NuxeoClient_QueryResult_descriptor,
        new java.lang.String[] { "TotalCount", "Docs", });
    internal_static_NuxeoClient_Document_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_NuxeoClient_Document_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NuxeoClient_Document_descriptor,
        new java.lang.String[] { "RepositoryName", "Uuid", "Name", "ParentPath", "Type", "Facets", "Schema", "State", "ParentRef", "ChangeToken", "Title", "LastModified", "VersionLabel", "LockOwner", "LockCreated", "IsCheckedOut", "Properties", });
    internal_static_NuxeoClient_Document_Schema_descriptor =
      internal_static_NuxeoClient_Document_descriptor.getNestedTypes().get(0);
    internal_static_NuxeoClient_Document_Schema_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NuxeoClient_Document_Schema_descriptor,
        new java.lang.String[] { "Name", "Prefix", });
    internal_static_NuxeoClient_Document_Property_descriptor =
      internal_static_NuxeoClient_Document_descriptor.getNestedTypes().get(1);
    internal_static_NuxeoClient_Document_Property_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NuxeoClient_Document_Property_descriptor,
        new java.lang.String[] { "Type", "Multiple", "ScalarValue", "ComplexValue", });
    internal_static_NuxeoClient_Document_Property_ScalarProperty_descriptor =
      internal_static_NuxeoClient_Document_Property_descriptor.getNestedTypes().get(0);
    internal_static_NuxeoClient_Document_Property_ScalarProperty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NuxeoClient_Document_Property_ScalarProperty_descriptor,
        new java.lang.String[] { "StrValue", "IntValue", "DoubleValue", "ByteValue", "BooleanValue", "Value", });
    internal_static_NuxeoClient_Document_Property_ComplexProperty_descriptor =
      internal_static_NuxeoClient_Document_Property_descriptor.getNestedTypes().get(1);
    internal_static_NuxeoClient_Document_Property_ComplexProperty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NuxeoClient_Document_Property_ComplexProperty_descriptor,
        new java.lang.String[] { "ComplexValue", });
    internal_static_NuxeoClient_Document_Property_ComplexProperty_ComplexValueEntry_descriptor =
      internal_static_NuxeoClient_Document_Property_ComplexProperty_descriptor.getNestedTypes().get(0);
    internal_static_NuxeoClient_Document_Property_ComplexProperty_ComplexValueEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NuxeoClient_Document_Property_ComplexProperty_ComplexValueEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_NuxeoClient_Document_PropertiesEntry_descriptor =
      internal_static_NuxeoClient_Document_descriptor.getNestedTypes().get(2);
    internal_static_NuxeoClient_Document_PropertiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NuxeoClient_Document_PropertiesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
