// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nuxeo.proto

package org.nuxeo.micro.repo.proto;

public interface QueryResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NuxeoClient.QueryResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 totalCount = 1;</code>
   */
  long getTotalCount();

  /**
   * <code>repeated .NuxeoClient.Document docs = 10;</code>
   */
  java.util.List<org.nuxeo.micro.repo.proto.Document> 
      getDocsList();
  /**
   * <code>repeated .NuxeoClient.Document docs = 10;</code>
   */
  org.nuxeo.micro.repo.proto.Document getDocs(int index);
  /**
   * <code>repeated .NuxeoClient.Document docs = 10;</code>
   */
  int getDocsCount();
  /**
   * <code>repeated .NuxeoClient.Document docs = 10;</code>
   */
  java.util.List<? extends org.nuxeo.micro.repo.proto.DocumentOrBuilder> 
      getDocsOrBuilderList();
  /**
   * <code>repeated .NuxeoClient.Document docs = 10;</code>
   */
  org.nuxeo.micro.repo.proto.DocumentOrBuilder getDocsOrBuilder(
      int index);
}
