// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nuxeo.proto

package org.nuxeo.micro.repo.proto;

public interface QueryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NuxeoClient.QueryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nxql = 1;</code>
   */
  java.lang.String getNxql();
  /**
   * <code>string nxql = 1;</code>
   */
  com.google.protobuf.ByteString
      getNxqlBytes();
}
