db:
  type: mongodb
  server: localhost:27017
  dbname: nuxeo

jwtIssuer: https://dev-XXXXXX.auth0.com

oauth:
  clientId: xxxxxxxxxxxxxxxxxxxxxxxxxx
  clientSecret: xxxxxxxxxxxxxxxxxxxxxxxxxx
  basePath: https://dev-XXXXXX.auth0.com
  tokenPath: /oauth/token
  authorizationPath: /authorize
  userInfoPath: /userinfo
  redirect_uri: http://localhost:8080/callback

port: 8080

nuxeo:
  tenantId: library
