// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nuxeo.proto

package org.nuxeo.micro.repo.service.grpc;

public interface DocumentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NuxeoClient.Document)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string repositoryName = 1;</code>
   */
  java.lang.String getRepositoryName();
  /**
   * <code>string repositoryName = 1;</code>
   */
  com.google.protobuf.ByteString
      getRepositoryNameBytes();

  /**
   * <code>string uuid = 2;</code>
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 2;</code>
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>string name = 3;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string path = 4;</code>
   */
  java.lang.String getPath();
  /**
   * <code>string path = 4;</code>
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>string type = 5;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 5;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>repeated string facets = 6;</code>
   */
  java.util.List<java.lang.String>
      getFacetsList();
  /**
   * <code>repeated string facets = 6;</code>
   */
  int getFacetsCount();
  /**
   * <code>repeated string facets = 6;</code>
   */
  java.lang.String getFacets(int index);
  /**
   * <code>repeated string facets = 6;</code>
   */
  com.google.protobuf.ByteString
      getFacetsBytes(int index);

  /**
   * <code>repeated .NuxeoClient.Document.Schema schema = 7;</code>
   */
  java.util.List<org.nuxeo.micro.repo.service.grpc.Document.Schema> 
      getSchemaList();
  /**
   * <code>repeated .NuxeoClient.Document.Schema schema = 7;</code>
   */
  org.nuxeo.micro.repo.service.grpc.Document.Schema getSchema(int index);
  /**
   * <code>repeated .NuxeoClient.Document.Schema schema = 7;</code>
   */
  int getSchemaCount();
  /**
   * <code>repeated .NuxeoClient.Document.Schema schema = 7;</code>
   */
  java.util.List<? extends org.nuxeo.micro.repo.service.grpc.Document.SchemaOrBuilder> 
      getSchemaOrBuilderList();
  /**
   * <code>repeated .NuxeoClient.Document.Schema schema = 7;</code>
   */
  org.nuxeo.micro.repo.service.grpc.Document.SchemaOrBuilder getSchemaOrBuilder(
      int index);

  /**
   * <code>string state = 8;</code>
   */
  java.lang.String getState();
  /**
   * <code>string state = 8;</code>
   */
  com.google.protobuf.ByteString
      getStateBytes();

  /**
   * <code>string parentRef = 9;</code>
   */
  java.lang.String getParentRef();
  /**
   * <code>string parentRef = 9;</code>
   */
  com.google.protobuf.ByteString
      getParentRefBytes();

  /**
   * <code>string changeToken = 10;</code>
   */
  java.lang.String getChangeToken();
  /**
   * <code>string changeToken = 10;</code>
   */
  com.google.protobuf.ByteString
      getChangeTokenBytes();

  /**
   * <code>string title = 11;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 11;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>int64 lastModified = 12;</code>
   */
  long getLastModified();

  /**
   * <code>string versionLabel = 13;</code>
   */
  java.lang.String getVersionLabel();
  /**
   * <code>string versionLabel = 13;</code>
   */
  com.google.protobuf.ByteString
      getVersionLabelBytes();

  /**
   * <code>string lockOwner = 14;</code>
   */
  java.lang.String getLockOwner();
  /**
   * <code>string lockOwner = 14;</code>
   */
  com.google.protobuf.ByteString
      getLockOwnerBytes();

  /**
   * <code>bool lockCreated = 15;</code>
   */
  boolean getLockCreated();

  /**
   * <code>bool isCheckedOut = 16;</code>
   */
  boolean getIsCheckedOut();

  /**
   * <code>map&lt;string, .NuxeoClient.Document.DataModel&gt; datamodel = 17;</code>
   */
  int getDatamodelCount();
  /**
   * <code>map&lt;string, .NuxeoClient.Document.DataModel&gt; datamodel = 17;</code>
   */
  boolean containsDatamodel(
      java.lang.String key);
  /**
   * Use {@link #getDatamodelMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, org.nuxeo.micro.repo.service.grpc.Document.DataModel>
  getDatamodel();
  /**
   * <code>map&lt;string, .NuxeoClient.Document.DataModel&gt; datamodel = 17;</code>
   */
  java.util.Map<java.lang.String, org.nuxeo.micro.repo.service.grpc.Document.DataModel>
  getDatamodelMap();
  /**
   * <code>map&lt;string, .NuxeoClient.Document.DataModel&gt; datamodel = 17;</code>
   */

  org.nuxeo.micro.repo.service.grpc.Document.DataModel getDatamodelOrDefault(
      java.lang.String key,
      org.nuxeo.micro.repo.service.grpc.Document.DataModel defaultValue);
  /**
   * <code>map&lt;string, .NuxeoClient.Document.DataModel&gt; datamodel = 17;</code>
   */

  org.nuxeo.micro.repo.service.grpc.Document.DataModel getDatamodelOrThrow(
      java.lang.String key);
}
