// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nuxeo.proto

package org.nuxeo.micro.repo.service.grpc;

/**
 * Protobuf type {@code NuxeoClient.QueryResult}
 */
public  final class QueryResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:NuxeoClient.QueryResult)
    QueryResultOrBuilder {
  // Use QueryResult.newBuilder() to construct.
  private QueryResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QueryResult() {
    totalCount_ = 0L;
    docs_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private QueryResult(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            totalCount_ = input.readInt64();
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              docs_ = new java.util.ArrayList<org.nuxeo.micro.repo.service.grpc.Document>();
              mutable_bitField0_ |= 0x00000002;
            }
            docs_.add(
                input.readMessage(org.nuxeo.micro.repo.service.grpc.Document.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        docs_ = java.util.Collections.unmodifiableList(docs_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.nuxeo.micro.repo.service.grpc.NuxeoClientProto.internal_static_NuxeoClient_QueryResult_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.nuxeo.micro.repo.service.grpc.NuxeoClientProto.internal_static_NuxeoClient_QueryResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.nuxeo.micro.repo.service.grpc.QueryResult.class, org.nuxeo.micro.repo.service.grpc.QueryResult.Builder.class);
  }

  private int bitField0_;
  public static final int TOTALCOUNT_FIELD_NUMBER = 1;
  private long totalCount_;
  /**
   * <code>int64 totalCount = 1;</code>
   */
  public long getTotalCount() {
    return totalCount_;
  }

  public static final int DOCS_FIELD_NUMBER = 5;
  private java.util.List<org.nuxeo.micro.repo.service.grpc.Document> docs_;
  /**
   * <code>repeated .NuxeoClient.Document docs = 5;</code>
   */
  public java.util.List<org.nuxeo.micro.repo.service.grpc.Document> getDocsList() {
    return docs_;
  }
  /**
   * <code>repeated .NuxeoClient.Document docs = 5;</code>
   */
  public java.util.List<? extends org.nuxeo.micro.repo.service.grpc.DocumentOrBuilder> 
      getDocsOrBuilderList() {
    return docs_;
  }
  /**
   * <code>repeated .NuxeoClient.Document docs = 5;</code>
   */
  public int getDocsCount() {
    return docs_.size();
  }
  /**
   * <code>repeated .NuxeoClient.Document docs = 5;</code>
   */
  public org.nuxeo.micro.repo.service.grpc.Document getDocs(int index) {
    return docs_.get(index);
  }
  /**
   * <code>repeated .NuxeoClient.Document docs = 5;</code>
   */
  public org.nuxeo.micro.repo.service.grpc.DocumentOrBuilder getDocsOrBuilder(
      int index) {
    return docs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (totalCount_ != 0L) {
      output.writeInt64(1, totalCount_);
    }
    for (int i = 0; i < docs_.size(); i++) {
      output.writeMessage(5, docs_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (totalCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, totalCount_);
    }
    for (int i = 0; i < docs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, docs_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.nuxeo.micro.repo.service.grpc.QueryResult)) {
      return super.equals(obj);
    }
    org.nuxeo.micro.repo.service.grpc.QueryResult other = (org.nuxeo.micro.repo.service.grpc.QueryResult) obj;

    boolean result = true;
    result = result && (getTotalCount()
        == other.getTotalCount());
    result = result && getDocsList()
        .equals(other.getDocsList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOTALCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalCount());
    if (getDocsCount() > 0) {
      hash = (37 * hash) + DOCS_FIELD_NUMBER;
      hash = (53 * hash) + getDocsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.nuxeo.micro.repo.service.grpc.QueryResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.nuxeo.micro.repo.service.grpc.QueryResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.nuxeo.micro.repo.service.grpc.QueryResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.nuxeo.micro.repo.service.grpc.QueryResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.nuxeo.micro.repo.service.grpc.QueryResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.nuxeo.micro.repo.service.grpc.QueryResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.nuxeo.micro.repo.service.grpc.QueryResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.nuxeo.micro.repo.service.grpc.QueryResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.nuxeo.micro.repo.service.grpc.QueryResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.nuxeo.micro.repo.service.grpc.QueryResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.nuxeo.micro.repo.service.grpc.QueryResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code NuxeoClient.QueryResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:NuxeoClient.QueryResult)
      org.nuxeo.micro.repo.service.grpc.QueryResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.nuxeo.micro.repo.service.grpc.NuxeoClientProto.internal_static_NuxeoClient_QueryResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.nuxeo.micro.repo.service.grpc.NuxeoClientProto.internal_static_NuxeoClient_QueryResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.nuxeo.micro.repo.service.grpc.QueryResult.class, org.nuxeo.micro.repo.service.grpc.QueryResult.Builder.class);
    }

    // Construct using org.nuxeo.micro.repo.service.grpc.QueryResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDocsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      totalCount_ = 0L;

      if (docsBuilder_ == null) {
        docs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        docsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.nuxeo.micro.repo.service.grpc.NuxeoClientProto.internal_static_NuxeoClient_QueryResult_descriptor;
    }

    public org.nuxeo.micro.repo.service.grpc.QueryResult getDefaultInstanceForType() {
      return org.nuxeo.micro.repo.service.grpc.QueryResult.getDefaultInstance();
    }

    public org.nuxeo.micro.repo.service.grpc.QueryResult build() {
      org.nuxeo.micro.repo.service.grpc.QueryResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.nuxeo.micro.repo.service.grpc.QueryResult buildPartial() {
      org.nuxeo.micro.repo.service.grpc.QueryResult result = new org.nuxeo.micro.repo.service.grpc.QueryResult(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.totalCount_ = totalCount_;
      if (docsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          docs_ = java.util.Collections.unmodifiableList(docs_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.docs_ = docs_;
      } else {
        result.docs_ = docsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.nuxeo.micro.repo.service.grpc.QueryResult) {
        return mergeFrom((org.nuxeo.micro.repo.service.grpc.QueryResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.nuxeo.micro.repo.service.grpc.QueryResult other) {
      if (other == org.nuxeo.micro.repo.service.grpc.QueryResult.getDefaultInstance()) return this;
      if (other.getTotalCount() != 0L) {
        setTotalCount(other.getTotalCount());
      }
      if (docsBuilder_ == null) {
        if (!other.docs_.isEmpty()) {
          if (docs_.isEmpty()) {
            docs_ = other.docs_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureDocsIsMutable();
            docs_.addAll(other.docs_);
          }
          onChanged();
        }
      } else {
        if (!other.docs_.isEmpty()) {
          if (docsBuilder_.isEmpty()) {
            docsBuilder_.dispose();
            docsBuilder_ = null;
            docs_ = other.docs_;
            bitField0_ = (bitField0_ & ~0x00000002);
            docsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDocsFieldBuilder() : null;
          } else {
            docsBuilder_.addAllMessages(other.docs_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.nuxeo.micro.repo.service.grpc.QueryResult parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.nuxeo.micro.repo.service.grpc.QueryResult) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long totalCount_ ;
    /**
     * <code>int64 totalCount = 1;</code>
     */
    public long getTotalCount() {
      return totalCount_;
    }
    /**
     * <code>int64 totalCount = 1;</code>
     */
    public Builder setTotalCount(long value) {
      
      totalCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 totalCount = 1;</code>
     */
    public Builder clearTotalCount() {
      
      totalCount_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<org.nuxeo.micro.repo.service.grpc.Document> docs_ =
      java.util.Collections.emptyList();
    private void ensureDocsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        docs_ = new java.util.ArrayList<org.nuxeo.micro.repo.service.grpc.Document>(docs_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.nuxeo.micro.repo.service.grpc.Document, org.nuxeo.micro.repo.service.grpc.Document.Builder, org.nuxeo.micro.repo.service.grpc.DocumentOrBuilder> docsBuilder_;

    /**
     * <code>repeated .NuxeoClient.Document docs = 5;</code>
     */
    public java.util.List<org.nuxeo.micro.repo.service.grpc.Document> getDocsList() {
      if (docsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(docs_);
      } else {
        return docsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .NuxeoClient.Document docs = 5;</code>
     */
    public int getDocsCount() {
      if (docsBuilder_ == null) {
        return docs_.size();
      } else {
        return docsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .NuxeoClient.Document docs = 5;</code>
     */
    public org.nuxeo.micro.repo.service.grpc.Document getDocs(int index) {
      if (docsBuilder_ == null) {
        return docs_.get(index);
      } else {
        return docsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .NuxeoClient.Document docs = 5;</code>
     */
    public Builder setDocs(
        int index, org.nuxeo.micro.repo.service.grpc.Document value) {
      if (docsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDocsIsMutable();
        docs_.set(index, value);
        onChanged();
      } else {
        docsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .NuxeoClient.Document docs = 5;</code>
     */
    public Builder setDocs(
        int index, org.nuxeo.micro.repo.service.grpc.Document.Builder builderForValue) {
      if (docsBuilder_ == null) {
        ensureDocsIsMutable();
        docs_.set(index, builderForValue.build());
        onChanged();
      } else {
        docsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .NuxeoClient.Document docs = 5;</code>
     */
    public Builder addDocs(org.nuxeo.micro.repo.service.grpc.Document value) {
      if (docsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDocsIsMutable();
        docs_.add(value);
        onChanged();
      } else {
        docsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .NuxeoClient.Document docs = 5;</code>
     */
    public Builder addDocs(
        int index, org.nuxeo.micro.repo.service.grpc.Document value) {
      if (docsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDocsIsMutable();
        docs_.add(index, value);
        onChanged();
      } else {
        docsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .NuxeoClient.Document docs = 5;</code>
     */
    public Builder addDocs(
        org.nuxeo.micro.repo.service.grpc.Document.Builder builderForValue) {
      if (docsBuilder_ == null) {
        ensureDocsIsMutable();
        docs_.add(builderForValue.build());
        onChanged();
      } else {
        docsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .NuxeoClient.Document docs = 5;</code>
     */
    public Builder addDocs(
        int index, org.nuxeo.micro.repo.service.grpc.Document.Builder builderForValue) {
      if (docsBuilder_ == null) {
        ensureDocsIsMutable();
        docs_.add(index, builderForValue.build());
        onChanged();
      } else {
        docsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .NuxeoClient.Document docs = 5;</code>
     */
    public Builder addAllDocs(
        java.lang.Iterable<? extends org.nuxeo.micro.repo.service.grpc.Document> values) {
      if (docsBuilder_ == null) {
        ensureDocsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, docs_);
        onChanged();
      } else {
        docsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .NuxeoClient.Document docs = 5;</code>
     */
    public Builder clearDocs() {
      if (docsBuilder_ == null) {
        docs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        docsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .NuxeoClient.Document docs = 5;</code>
     */
    public Builder removeDocs(int index) {
      if (docsBuilder_ == null) {
        ensureDocsIsMutable();
        docs_.remove(index);
        onChanged();
      } else {
        docsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .NuxeoClient.Document docs = 5;</code>
     */
    public org.nuxeo.micro.repo.service.grpc.Document.Builder getDocsBuilder(
        int index) {
      return getDocsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .NuxeoClient.Document docs = 5;</code>
     */
    public org.nuxeo.micro.repo.service.grpc.DocumentOrBuilder getDocsOrBuilder(
        int index) {
      if (docsBuilder_ == null) {
        return docs_.get(index);  } else {
        return docsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .NuxeoClient.Document docs = 5;</code>
     */
    public java.util.List<? extends org.nuxeo.micro.repo.service.grpc.DocumentOrBuilder> 
         getDocsOrBuilderList() {
      if (docsBuilder_ != null) {
        return docsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(docs_);
      }
    }
    /**
     * <code>repeated .NuxeoClient.Document docs = 5;</code>
     */
    public org.nuxeo.micro.repo.service.grpc.Document.Builder addDocsBuilder() {
      return getDocsFieldBuilder().addBuilder(
          org.nuxeo.micro.repo.service.grpc.Document.getDefaultInstance());
    }
    /**
     * <code>repeated .NuxeoClient.Document docs = 5;</code>
     */
    public org.nuxeo.micro.repo.service.grpc.Document.Builder addDocsBuilder(
        int index) {
      return getDocsFieldBuilder().addBuilder(
          index, org.nuxeo.micro.repo.service.grpc.Document.getDefaultInstance());
    }
    /**
     * <code>repeated .NuxeoClient.Document docs = 5;</code>
     */
    public java.util.List<org.nuxeo.micro.repo.service.grpc.Document.Builder> 
         getDocsBuilderList() {
      return getDocsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.nuxeo.micro.repo.service.grpc.Document, org.nuxeo.micro.repo.service.grpc.Document.Builder, org.nuxeo.micro.repo.service.grpc.DocumentOrBuilder> 
        getDocsFieldBuilder() {
      if (docsBuilder_ == null) {
        docsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.nuxeo.micro.repo.service.grpc.Document, org.nuxeo.micro.repo.service.grpc.Document.Builder, org.nuxeo.micro.repo.service.grpc.DocumentOrBuilder>(
                docs_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        docs_ = null;
      }
      return docsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:NuxeoClient.QueryResult)
  }

  // @@protoc_insertion_point(class_scope:NuxeoClient.QueryResult)
  private static final org.nuxeo.micro.repo.service.grpc.QueryResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.nuxeo.micro.repo.service.grpc.QueryResult();
  }

  public static org.nuxeo.micro.repo.service.grpc.QueryResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QueryResult>
      PARSER = new com.google.protobuf.AbstractParser<QueryResult>() {
    public QueryResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new QueryResult(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<QueryResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<QueryResult> getParserForType() {
    return PARSER;
  }

  public org.nuxeo.micro.repo.service.grpc.QueryResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

