// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nuxeo.proto

package org.nuxeo.micro.repo.service.grpc;

public interface QueryResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NuxeoClient.QueryResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 totalCount = 1;</code>
   */
  long getTotalCount();

  /**
   * <code>repeated .NuxeoClient.Document docs = 5;</code>
   */
  java.util.List<org.nuxeo.micro.repo.service.grpc.Document> 
      getDocsList();
  /**
   * <code>repeated .NuxeoClient.Document docs = 5;</code>
   */
  org.nuxeo.micro.repo.service.grpc.Document getDocs(int index);
  /**
   * <code>repeated .NuxeoClient.Document docs = 5;</code>
   */
  int getDocsCount();
  /**
   * <code>repeated .NuxeoClient.Document docs = 5;</code>
   */
  java.util.List<? extends org.nuxeo.micro.repo.service.grpc.DocumentOrBuilder> 
      getDocsOrBuilderList();
  /**
   * <code>repeated .NuxeoClient.Document docs = 5;</code>
   */
  org.nuxeo.micro.repo.service.grpc.DocumentOrBuilder getDocsOrBuilder(
      int index);
}
